management:
  endpoints:
    web:
      exposure:
        include: metrics,health,env
  endpoint:
    env:
      show-values: ALWAYS

blitzpay:
  voice:
    whisper:
      base-url: http://whisper:8000/v1