name: Test Application

on:
  workflow_call:
    inputs:
      gradle-args:
        description: "Additional Gradle arguments"
        required: false
        type: string
        default: ""

jobs:
  test:
    permissions:
      contents: read
    uses: medimohammadise/elegant-ci-cd-pipeline/.github/workflows/back-end-gradle-test.yml@45ad664
    with:
      gradle-args: ${{ inputs.gradle-args }}
      unit-test-task: test
      integration-test-task: help
